const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

const devMode = process.env.NODE_ENV !== 'production'

module.exports = {
  // entry point
  entry: './src/js/app.js',

  mode: process.env.NODE_ENV,

  // output must be absolute
  // totul merge in dist afr de index.html
  output: {
    path: path.join(__dirname, 'dist/assets'),
    filename: 'bundle.js'
  },

  // loaders are transformations that are
  // applied on the source code of a module
  module: {
    rules: [{
      test: /\.js$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader'
      }
    }, {
      test: /\.(sa|sc|c)ss$/,
      use: [
        {
          loader: MiniCssExtractPlugin.loader,
          options: {
            hmr: process.env.NODE_ENV === 'development'
          }
        },
        {
          loader: 'css-loader',
          options: {
            sourceMap: true
          }
        },
        {
          loader: 'sass-loader',
          options: {
            sourceMap: true
          }
        }
      ]
    }]
  },

  plugins: [
    new MiniCssExtractPlugin({
      filename: devMode ? '[name].css' : '[name].[hash].css',
      chunkFilename: devMode ? '[id].css' : '[id].[hash].css'
    }),
    new HtmlWebpackPlugin({
      inject: 'body', // Inject all files that are generated by webpack, e.g. bundle.js
      hash: true,
      template: './src/index.html',
      filename: process.env.NODE_ENV === 'development' ? 'index.html' : '../index.html' // put it outside dist when building for production
    })
  ],

  // source maps
  devtool: process.env.NODE_ENV === 'development' ? 'cheap-module-source-map' : 'source-map',

  // dev server config
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    hot: true,
    historyApiFallback: true
  }
}
